# Generated by Django 4.1.5 on 2023-03-04 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agora_token', models.TextField(max_length=500)),
                ('start_time', models.DateField(auto_now_add=True)),
                ('end_time', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(auto_now_add=True)),
                ('end_time', models.DateField(null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAuth.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.TextField(default='', max_length=500)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAuth.presenter')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAuth.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_body', models.CharField(default='', max_length=250)),
                ('count', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAuth.poll')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField(default=False)),
                ('is_presenter', models.BooleanField(default=False)),
                ('join_time', models.DateField(auto_now_add=True)),
                ('left_time', models.DateField(null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAuth.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttentionScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('attention_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAuth.meeting')),
            ],
        ),
    ]
