# Generated by Django 4.1.5 on 2023-03-04 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyAuth', '0002_meeting_presenter_poll_options_meetinguser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinguser',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyAuth.meeting'),
        ),
        migrations.AlterField(
            model_name='meetinguser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
