# Generated by Django 4.1.5 on 2023-04-22 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyAuth', '0004_alter_meetinguser_meeting_alter_meetinguser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='channel_name',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='meetinguser',
            name='left_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='MyAuth.settings'),
        ),
    ]
