# Generated by Django 4.1.5 on 2023-04-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAuth', '0005_meeting_channel_name_alter_meetinguser_left_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinguser',
            name='agora_id',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
