# Generated by Django 4.1.5 on 2023-04-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAuth', '0006_meetinguser_agora_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinguser',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
