# Generated by Django 4.1.5 on 2023-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAuth', '0008_meetinguser_alert_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinguser',
            name='alert_num',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
